### ISSUE TITLE
The mkinitramfs tool does not work

### ISSUE THREAD

**Issue by Difrex** [sp00f1ng/boobstrap#1]
Hi,

I just trying to create a Manjaro initramfs image and build failing at step 3.

Steps to reproduce:

1. Create the Manjaro/Arch base chroot
```
mkdir chroot
pacstrap chroot base
```

2. Launch mkinitramfs
```
sudo mkinitramfs initramfs/ \
                --overlay chroot/ \
                --command 'mksquashfs {source} {destination} -b 1048576 -comp xz -Xdict-size 100%'
                --output $PWD/initrd
```

3. Got an error
```
ldd: ./=>: Нет такого файла или каталога
SKIP OUTPUT
install: не удалось выполнить stat для '=>': Нет такого файла или каталога
SKIP OUTPUT
```

**Comment by sp00f1ng** [comment]
Thanks, I will fix to it.

Try to use "--overlay chroot", without backslash for now.

Also you can use --squashfs-xz instead of full command, because syntax can change, {SOURCE} instead of {source} and {DESTINATION} instead of {destination}.

**Comment by sp00f1ng** [comment]
// Fixed.

**Comment by Difrex** [comment]
An error still exists but initramfs image is created.

The next problems that I received are the wrong working of the mkbootisofs too.
* Where can I get a `cdboot.img` file?
* The `locate` is a not core tool. Maybe rewrite this script in a more portable way?
* Add license please to allow contributions to your project
